apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-green
  # these labels are replicaset labels
  labels:
    project: roboshop
    tier: frontend
    component: frontend
    version: green
spec:
  replicas: 4
  selector:
    # using these labels replica set selects the pod
    matchLabels:
      project: roboshop
      tier: frontend
      component: frontend
      version: green
  # This is pod definition, pod is subset of replicaset
  template:
    metadata:
      labels:
        project: roboshop
        tier: frontend
        component: frontend
        version: green
    spec:
      containers:
      - name: nginx-green
        image: jujjurisowjanya/blue-green:2.0.0


