apiVersion: v1
kind: Service
metadata:
  name: nginx-preview
spec:
  selector:
    # labels are used as selectors
    project: roboshop
    tier: frontend
    component: frontend
    version: green
  ports:
  - protocol: TCP
    port: 80 # servie port
    targetPort: 80 # container port
